Update common-actions.yaml

diff --git a/.github/workflows/common-actions.yaml b/.github/workflows/common-actions.yaml
--- a/.github/workflows/common-actions.yaml
+++ b/.github/workflows/common-actions.yaml
@@ -3,10 +3,40 @@ name: Lint
 on: [push, pull_request]
 
 jobs:
-  lint:
+  build:
+    # We want to run on external PRs, but not on our own internal PRs as they'll be run
+    # by the push to the branch. Without this if check, checks are duplicated since
+    # internal PRs match both the push and pull_request events.
+    if:
+      github.event_name == 'push' || github.event.pull_request.head.repo.full_name !=
+      github.repository
+
     runs-on: ubuntu-latest
+
     steps:
       - uses: actions/checkout@v3
-      - uses: psf/black@stable
-      - with:
-          args: "--disable=E0401,C0116"
+
+      - name: Assert PR target is main
+        if: github.event_name == 'pull_request' && github.repository == 'psf/black'
+        run: |
+          if [ "$GITHUB_BASE_REF" != "master" ]; then
+              echo "::error::PR targeting '$GITHUB_BASE_REF', please refile targeting 'master'." && exit 1
+          fi
+
+      - name: Set up latest Python
+        uses: actions/setup-python@v4
+        with:
+          python-version: "*"
+
+      - name: Install dependencies
+        run: |
+          python -m pip install --upgrade pip
+          python -m pip install -e '.[d]'
+          python -m pip install tox
+
+      - name: Run pre-commit hooks
+        uses: pre-commit/action@v3.0.0
+
+      - name: Format ourselves
+        run: |
+          tox -e run_self
